# This is a basic workflow that is manually triggered

name: Rebuild cache

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency: ['dep_julia', 'dep_julia_packages', 'dep_llvm', 'dep_juce']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get source code
      run: |
        git clone https://github.com/joshua-maros/audiobench.git -b beta --depth 1
    - name: Execute ./build.py ${{ matrix.dependency }}
      run: |
        cd audiobench
        ./build.py ${{ matrix.dependency }}
    - name: Upload result
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ matrix.dependency }}
        path: audiobench/dependencies/
        if-no-files-found: error
  
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v2.0.8
        with:
          name: dep_julia
      - name: IDK
        run: |
          ls
          ls *
          ls */*
